<a href="https://colab.research.google.com/github/kmerchan/holbertonschool-machine_learning/blob/main/SARSA_of_lambda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x


In [ ]:
import gym
import numpy as np


def epsilon_greedy(Q, state, epsilon):
    """                                                                                                                 
    Uses epsilon-greedy to determine if the reinforcement learning is                                                   
       exploring or exploiting and uses to get action                                                                   
                                                                                                                        
    parameters:                                                                                                         
        Q [numpy.ndarray of shape (s, a)]: contains the Q table                                                         
        state: the current state                                                                                        
        epsilon: the threshold for epsilon-greedy                                                                       
                                                                                                                        
    returns:                                                                                                            
        the action to take                                                                                              
    """
    # determine exploring-exploiting balance by comparing to epsilon                                                    
    if np.random.uniform(0, 1) < epsilon:
        # exploring                                                                                                     
        action = np.random.randint(Q.shape[1])
    else:
        # exploiting                                                                                                    
        action = np.argmax(Q[state, :])
    return action

def sarsa_lambtha(env, Q, lambtha, episodes=5000, max_steps=100, alpha=0.1,
                  gamma=0.99, epsilon=1, min_epsilon=0.1, epsilon_decay=0.05):
    """                                                                                                                 
    Performs the SARSA(λ) algorithm                                                                                     
                                                                                                                        
    parameters:                                                                                                         
        env: the openAI environment instance                                                                            
        Q [numpy.ndarray of shape(s, a)]: contains the Q table                                                          
        lambtha: the eligibility trace factor                                                                           
        episodes [int]: total number of episodes to train over                                                          
        max_steps [int]: the maximum number of steps per episode                                                        
        alpha [float]: the learning rate                                                                                
        gamma [float]: the discount rate                                                                                
        epsilon: the initial threshold for epsilon greedy                                                               
        min_epsilon [float]: the minimum value that epsilon should decay to                                             
        epsilon_decay [float]: decay rate for updating epsilon between episodes                                         
                                                                                                                        
    returns:                                                                                                            
        Q: the updated Q table                                                                                          
    """
    # set maximum epsilon to the current epsilon before epsilon_decay                                                   
    max_epsilon = epsilon
    # Sets the eligibility traces to numpy array of zeros of same shape as Q                                            
    Et = np.zeros((Q.shape))
    # iterate over all episodes                                                                                         
    for ep in range(episodes):
        # set the initial state of each episode to environment reset                                                    
        state = env.reset()
        # get the action from epsilon-greedy function                                                                   
        action = epsilon_greedy(Q, state, epsilon)
        # iterate up to maximum number of steps per episode                                                             
        for step in range(max_steps):
            # eligibility traces updated with lambda & gamma                                                            
            Et = Et * lambtha * gamma
            # increase Et for current state, action                                                                     
            Et[state, action] += 1

            # perform the action to get next_state, reward, done, and info                                              
            next_state, reward, done, info = env.step(action)
            # update the action, using epsilon-greedy again                                                             
            next_action = epsilon_greedy(Q, state, epsilon)

            # if the algorithm finds a hole, the reward is updated to -1                                                
            if env.desc.reshape(env.observation_space.n)[next_state] == b'H':
                reward = -1
            # if the algorithm finds the goal, the reward is updated to 1                                               
            if env.desc.reshape(env.observation_space.n)[next_state] == b'G':
                reward = 1

            # calculate delta_t                                                                                         
            # delta_t = R(t + 1) + gamma * Q(St + 1, At + 1) - Q(St, At)                                                
            delta_t = reward + (
                gamma * Q[next_state, next_action]) - Q[state, action]
            # upddate Q table                                                                                           
            # Q(st) = Q(st) + alpha * delta_t * Et(St)                                                                  
            Q[state, action] = Q[state, action] + (
                alpha * delta_t * Et[state, action])
            # if done, break out of episode                                                                             
            if done:
                break
            # otherwise, reset state, action and continue                                                               
            state = next_state
            action = next_action
        # after each epsiode, update epsilon to decay                                                                   
        # epsilon will now favor slightly more exploitation than exploration                                            
        epsilon = min_epsilon + (
            (max_epsilon - min_epsilon) * np.exp(-epsilon_decay * ep))
    # when all episodes completed, return updated Q table                                                               
    return Q

np.random.seed(0)
env = gym.make('FrozenLake8x8-v0')
Q = np.random.uniform(size=(64, 4))
np.set_printoptions(precision=4)
print(sarsa_lambtha(env, Q, 0.9))


[[ 3.3879e-02  3.4557e-02  2.8270e-02  6.8923e-02]
 [ 3.0917e-02  3.4431e-02  3.9018e-02  9.7059e-02]
 [ 3.3157e-02  6.5353e-02  3.8297e-02  1.2059e-01]
 [ 8.2652e-02  6.8969e-02  2.7514e-02  1.4684e-01]
 [ 1.1357e-01  1.3502e-01  1.8097e-01  2.0670e-01]
 [ 1.9114e-01  2.1386e-01  2.8810e-01  2.7593e-01]
 [ 2.7993e-01  2.8333e-01  3.5798e-01  2.8041e-01]
 [ 2.9931e-01  3.4318e-01  3.4009e-01  3.0604e-01]
 [ 9.6911e-04 -8.1240e-03 -1.7234e-02  3.0431e-02]
 [-5.2000e-03 -2.7483e-02 -2.6210e-02  4.4929e-02]
 [-1.6855e-02 -8.6340e-02 -1.1419e-01  6.6851e-02]
 [-1.9790e-01 -2.9562e-01 -3.7827e-01  1.0026e-01]
 [-5.2111e-03 -1.0407e-01  2.6291e-02  1.2932e-01]
 [ 1.3394e-01  1.6509e-01  2.3974e-01  2.3793e-01]
 [ 2.5915e-01  2.5940e-01  3.8330e-01  3.0308e-01]
 [ 3.5390e-01  3.6438e-01  4.1513e-01  3.1072e-01]
 [-5.5764e-02 -6.2489e-02 -6.9592e-02 -5.7046e-02]
 [-7.6281e-02 -9.2457e-02 -8.5647e-02 -9.0307e-02]
 [-1.1340e-01 -2.5187e-01 -1.7623e-01 -2.2651e-01]
 [ 2.8281e-01  1.2020e-01  2.96