<a href="https://colab.research.google.com/github/kmerchan/holbertonschool-machine_learning/blob/main/TD_of_lambda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x


In [ ]:
import gym
import numpy as np


def td_lambtha(env, V, policy, lambtha, episodes=5000, max_steps=100,
               alpha=0.1, gamma=0.99):
    """                                                                                                                 
    Performs the TD(λ) algorithm                                                                                        
                                                                                                                        
    parameters:                                                                                                         
        env: the openAI environment instance                                                                            
        V [numpy.ndarray of shape(s,)]: contains the value estimate                                                     
        policy: function that takes in state & returns the next action to take                                          
        episodes [int]: total number of episodes to train over                                                          
        max_steps [int]: the maximum number of steps per episode                                                        
        alpha [float]: the learning rate                                                                                
        gamma [float]: the discount rate                                                                                
                                                                                                                        
    returns:                                                                                                            
        V: the updated value estimate                                                                                   
    """
    episode = [[], []]
    Et = [0 for i in range(env.observation_space.n)]
    for ep in range(episodes):
        state = env.reset()
        for step in range(max_steps):
            Et = list(np.array(Et) * lambtha * gamma)
            Et[state] += 1

            action = policy(state)
            next_state, reward, done, info = env.step(action)

            if env.desc.reshape(env.observation_space.n)[next_state] == b'H':
                reward = -1

            if env.desc.reshape(env.observation_space.n)[next_state] == b'G':
                reward = 1

            delta_t = reward + gamma * V[next_state] - V[state]

            V[state] = V[state] + alpha * delta_t * Et[state]

            if done:
                break
            state = next_state
    return np.array(V)

np.random.seed(0)

env = gym.make('FrozenLake8x8-v0')
LEFT, DOWN, RIGHT, UP = 0, 1, 2, 3

def policy(s):
    p = np.random.uniform()
    if p > 0.5:
        if s % 8 != 7 and env.desc[s // 8, s % 8 + 1] != b'H':
            return RIGHT
        elif s // 8 != 7 and env.desc[s // 8 + 1, s % 8] != b'H':
            return DOWN
        elif s // 8 != 0 and env.desc[s // 8 - 1, s % 8] != b'H':
            return UP
        else:
            return LEFT
    else:
        if s // 8 != 7 and env.desc[s // 8 + 1, s % 8] != b'H':
            return DOWN
        elif s % 8 != 7 and env.desc[s // 8, s % 8 + 1] != b'H':
            return RIGHT
        elif s % 8 != 0 and env.desc[s // 8, s % 8 - 1] != b'H':
            return LEFT
        else:
            return UP

V = np.where(env.desc == b'H', -1, 1).reshape(64).astype('float64')
np.set_printoptions(precision=4)
print(td_lambtha(env, V, policy, 0.9).reshape((8, 8)))


[[-1.7024 -1.6418 -1.6322 -1.5696 -1.4827 -1.4578 -1.4339 -1.4317]
 [-1.7394 -1.7526 -1.7903 -1.8128 -1.6445 -1.5156 -1.4666 -1.4487]
 [-1.8045 -1.8105 -1.9037 -1.     -1.7291 -1.672  -1.5307 -1.4744]
 [-1.84   -1.8541 -1.9022 -1.9559 -1.8631 -1.     -1.676  -1.3938]
 [-1.8805 -1.927  -1.9208 -1.     -1.72   -1.5595 -1.4392 -0.9263]
 [-1.9187 -1.     -1.      0.9989 -1.7327 -1.5748 -1.     -0.8238]
 [-1.8715 -1.     -0.374  -0.2578 -1.     -1.2385 -1.     -0.0967]
 [-1.5725 -1.3142 -1.487  -1.      1.      0.3808  0.3299  1.    ]]
